import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // next-env.d.ts is autogenerated by Next.js on every dev/build run - never hand-edited, not
    // worth linting.
    // .netlify holds the adapter's compiled copy of .next - thousands of
    // errors in minified output that drown out any real one in source.
    ignores: [".next/**", ".netlify/**", "node_modules/**", "next-env.d.ts"],
  },
];

export default eslintConfig;
